#!/bin/bash

# =================================================================
# ESEMPIO DI CONFIGURAZIONE PERSONALIZZATA FINESTRE TERMINALI
# =================================================================
# Questo file mostra esempi di come personalizzare le dimensioni
# e il posizionamento delle finestre modificando le costanti 
# all'inizio degli script startmas.sh e startmas_modular.sh
# =================================================================

echo "=== ESEMPI DI CONFIGURAZIONE FINESTRE TERMINALI ==="
echo ""

echo "1. CONFIGURAZIONE DEFAULT (attuale):"
echo "   # Posizionamento"
echo "   WINDOW_START_X=100"
echo "   WINDOW_START_Y=100" 
echo "   WINDOW_OFFSET=50"
echo ""
echo "   # Dimensioni macOS (pixel)"
echo "   WINDOW_WIDTH_MACOS=400"
echo "   WINDOW_HEIGHT_MACOS=300"
echo ""
echo "   # Dimensioni Linux (caratteri)" 
echo "   WINDOW_COLS_LINUX=40"
echo "   WINDOW_ROWS_LINUX=12"
echo ""

echo "2. CONFIGURAZIONE FINESTRE PIU' GRANDI:"
echo "   # Posizionamento"
echo "   WINDOW_START_X=50"
echo "   WINDOW_START_Y=50"
echo "   WINDOW_OFFSET=60"
echo ""
echo "   # Dimensioni macOS (pixel)"
echo "   WINDOW_WIDTH_MACOS=600"
echo "   WINDOW_HEIGHT_MACOS=450"
echo ""
echo "   # Dimensioni Linux (caratteri)"
echo "   WINDOW_COLS_LINUX=60" 
echo "   WINDOW_ROWS_LINUX=18"
echo ""

echo "3. CONFIGURAZIONE FINESTRE PICCOLE CON MAGGIORE SPAZIATURA:"
echo "   # Posizionamento"
echo "   WINDOW_START_X=150"
echo "   WINDOW_START_Y=150"
echo "   WINDOW_OFFSET=80"
echo ""
echo "   # Dimensioni macOS (pixel)"
echo "   WINDOW_WIDTH_MACOS=300"
echo "   WINDOW_HEIGHT_MACOS=200"
echo ""
echo "   # Dimensioni Linux (caratteri)"
echo "   WINDOW_COLS_LINUX=30"
echo "   WINDOW_ROWS_LINUX=8"
echo ""

echo "4. CONFIGURAZIONE PER MONITOR GRANDI:"
echo "   # Posizionamento" 
echo "   WINDOW_START_X=200"
echo "   WINDOW_START_Y=200"
echo "   WINDOW_OFFSET=100"
echo ""
echo "   # Dimensioni macOS (pixel)"
echo "   WINDOW_WIDTH_MACOS=800"
echo "   WINDOW_HEIGHT_MACOS=600"
echo ""
echo "   # Dimensioni Linux (caratteri)"
echo "   WINDOW_COLS_LINUX=80"
echo "   WINDOW_ROWS_LINUX=24"
echo ""

echo "==================================================================="
echo "Per applicare una configurazione:"
echo "1. Copia le costanti desiderate"
echo "2. Modifica la sezione 'CONFIGURAZIONE FINESTRE TERMINALI'"
echo "   all'inizio di startmas.sh o startmas_modular.sh"
echo "3. Salva e esegui lo script"
echo "==================================================================="
echo ""
echo "NOTA: Le dimensioni sono espresse in:"
echo "- macOS: pixel (larghezza x altezza)"
echo "- Linux: caratteri (colonne x righe)"
echo ""
echo "L'offset determina la distanza tra finestre nell'effetto cascata"
echo "===================================================================" 